from collections.abc import Iterator

from app.services.llm.base import LLMProvider


class LocalStubLLMProvider(LLMProvider):
    def stream_chat(self, system_prompt: str, messages: list[dict], context_chunks: list[dict]) -> Iterator[str]:
        del system_prompt
        question = messages[-1]['content'] if messages else ''
        sources = ', '.join([f'[{i + 1}]' for i, _ in enumerate(context_chunks)])
        if context_chunks:
            full = (
                '## Direct Answer\n'
                '[local-stub] This response is generated by the local placeholder provider.\n\n'
                f'Question received: {question}\n\n'
                '## Key Points\n'
                '- This is a deterministic local stub answer.\n'
                '- Source references are placeholders for development.\n\n'
                '## Evidence\n'
                f'- Available sources: {sources}'
            )
        else:
            full = (
                '## Direct Answer\n'
                '[local-stub] No indexed sources were found.\n\n'
                '## Key Points\n'
                '- Index your documents first.\n'
                '- Retry the question after indexing completes.\n\n'
                '## Evidence\n'
                '- No source chunks were available.'
            )
        for token in full.split(' '):
            yield token + ' '
